version: "3.3"

services:
  app:
    image: oeffikator
    build:
      context: .
      dockerfile: oeffikator/Dockerfile
    ports:
      - 8000:8000
    environment:
      OEFFI_DB_NAME: ${OEFFI_DB_NAME}
      OEFFI_DB_CONTAINER_NAME: ${OEFFI_DB_CONTAINER_NAME}
      OEFFI_MAX_WEST: ${OEFFI_MAX_WEST}
      OEFFI_MAX_EAST: ${OEFFI_MAX_EAST}
      OEFFI_MAX_SOUTH: ${OEFFI_MAX_SOUTH}
      OEFFI_MAX_NORTH: ${OEFFI_MAX_NORTH}
    depends_on:
      db:
        condition: service_healthy
      bvg-api:
        condition: service_healthy
    secrets:
      - oeffi_db_user
      - oeffi_db_pw
    container_name: ${OEFFI_APP_CONTAINER_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo $(( $(curl --write-out '%{http_code}\n' --silent --output /dev/null  localhost:8000/alive) == 200 ? 0 : 1 ))"
        ]
      interval: 5s
      timeout: 5s
      retries: 3

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/oeffi_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/oeffi_db_pw
      POSTGRES_DB: ${OEFFI_DB_NAME}
    secrets:
      - oeffi_db_user
      - oeffi_db_pw
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data:rw
    container_name: ${OEFFI_DB_CONTAINER_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $(cat /run/secrets/oeffi_db_user) -d ${OEFFI_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 3

  visualization:
    image: visualization
    build:
      context: .
      dockerfile: visualization/Dockerfile
    ports:
      - "80:80"
    environment:
      OEFFI_APP_CONTAINER_NAME: ${OEFFI_APP_CONTAINER_NAME}
      OEFFI_MAX_WEST: ${OEFFI_MAX_WEST}
      OEFFI_MAX_EAST: ${OEFFI_MAX_EAST}
      OEFFI_MAX_SOUTH: ${OEFFI_MAX_SOUTH}
      OEFFI_MAX_NORTH: ${OEFFI_MAX_NORTH}
    depends_on:
      app:
        condition: service_healthy

  bvg-api:
    image: derhuerst/bvg-rest:6
    ports:
      - "3000:3000"    
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 0"
        ]
      interval: 5s
      timeout: 5s
      retries: 3

secrets:
  oeffi_db_pw:
    file: oeffikator_db_pw.txt
  oeffi_db_user:
    file: oeffikator_db_user.txt

volumes:
  pgdata:
