[tool.poetry]
name = "oeffikator"
version = "0.1.0"
description = "A visualisation tool for commuting times on public transport"
authors = ["Eric Kolibacz <e.kolibacz@yahoo.de>"]
license = "GNU GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.2"
numpy = "^1.24.0"
matplotlib = "^3.6.2"
scipy = "^1.9.3"
requests = "^2.28.1"
geopy = "^2.3.0"
nest-asyncio = "^1.5.6"
jupyter = "^1.0.0"
scikit-learn = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-env = "^0.8.0"
pytest-dotenv = "^0.5.2"
black = "^22.3.0"
isort = "^5.6.4"
pylint = "^2.8.3"
pycodestyle = "^2.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.pylint."MASTER"]
ignored-modules = ["pydantic"]

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120
disable = "R,C,W0613,W0703,E0213,W0511,W0221"