# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Style Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Reformat code with black
      run: |
        poetry run black oeffikator/ tests/
    - name: Sort imports with isort
      run: |
        poetry run isort oeffikator/ tests/
    - name: Check Code Sytel with pycodestyle
      run: |
        poetry run pycodestyle oeffikator/ tests/
    - name: Lint Code with pylint
      run: |
        poetry run pylint oeffikator/ tests/
    - name: Lint jupyter notebooks
      run: |  # black has own jupyter notebook support
        poetry run nbqa isort oeffikator/
        poetry run nbqa pylint oeffikator/
        poetry run nbqa pycodestyle oeffikator/
